# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{text-table}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Tinio"]
  s.date = %q{2010-02-25}
  s.description = %q{Allows you to easily create and format plain text tables, useful when working with the terminal or when you want to quickly print formatted tables to a dot-matrix printer.}
  s.email = %q{aptinio@yahoo.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/text-table.rb",
     "lib/text-table/cell.rb",
     "lib/text-table/enumerable.rb",
     "lib/text-table/row.rb",
     "lib/text-table/symbol.rb",
     "lib/text-table/table.rb",
     "spec/cell_spec.rb",
     "spec/enumerable_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/table_spec.rb",
     "text-table.gemspec"
  ]
  s.homepage = %q{http://github.com/aptinio/text-table}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A feature-rich, easy-to-use plain text table formatter.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/cell_spec.rb",
     "spec/table_spec.rb",
     "spec/enumerable_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

